//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Activos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BMS_DATA_DENTEntities : DbContext
    {
        public BMS_DATA_DENTEntities()
            : base("name=BMS_DATA_DENTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<INV_GARA> INV_GARA { get; set; }
        public virtual DbSet<INV_MOV1> INV_MOV1 { get; set; }
        public virtual DbSet<INV_PROD> INV_PROD { get; set; }
        public virtual DbSet<SGA_PERMISOS> SGA_PERMISOS { get; set; }
        public virtual DbSet<SGA_ROLES> SGA_ROLES { get; set; }
        public virtual DbSet<SGA_ROLES_PERMISOS> SGA_ROLES_PERMISOS { get; set; }
        public virtual DbSet<SGA_USUARIOS> SGA_USUARIOS { get; set; }
        public virtual DbSet<INV_MOVS> INV_MOVS { get; set; }
        public virtual DbSet<SGA_BITACORA_TICKET> SGA_BITACORA_TICKET { get; set; }
        public virtual DbSet<SGA_AFILIADOS> SGA_AFILIADOS { get; set; }
        public virtual DbSet<WEB_Canton> WEB_Canton { get; set; }
        public virtual DbSet<WEB_Distrito> WEB_Distrito { get; set; }
        public virtual DbSet<WEB_Provincia> WEB_Provincia { get; set; }
        public virtual DbSet<SGA_BITACORA_SERIE> SGA_BITACORA_SERIE { get; set; }
        public virtual DbSet<SGA_EXEPCIONES> SGA_EXEPCIONES { get; set; }
        public virtual DbSet<INV_TECN> INV_TECN { get; set; }
        public virtual DbSet<INV_GARV> INV_GARV { get; set; }
        public virtual DbSet<SGA_CATEGORY_PRODUCT> SGA_CATEGORY_PRODUCT { get; set; }
        public virtual DbSet<INV_DANOS> INV_DANOS { get; set; }
        public virtual DbSet<SGA_CAMBIO_AFILIADO> SGA_CAMBIO_AFILIADO { get; set; }
        public virtual DbSet<SGA_ESTADO_PRODUCTOS> SGA_ESTADO_PRODUCTOS { get; set; }
        public virtual DbSet<SGA_EVIDENCIA_TICKET> SGA_EVIDENCIA_TICKET { get; set; }
    
        public virtual ObjectResult<string> SGA_STATUS_SERIES(string p_serie_validar, string p_num_ticket)
        {
            var p_serie_validarParameter = p_serie_validar != null ?
                new ObjectParameter("p_serie_validar", p_serie_validar) :
                new ObjectParameter("p_serie_validar", typeof(string));
    
            var p_num_ticketParameter = p_num_ticket != null ?
                new ObjectParameter("p_num_ticket", p_num_ticket) :
                new ObjectParameter("p_num_ticket", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SGA_STATUS_SERIES", p_serie_validarParameter, p_num_ticketParameter);
        }
    
        public virtual int SGA_ACTUALIZAR_ESTATUS_PRODUCTO_AFILIADO(string num_afiliado, string serie_consecutivo)
        {
            var num_afiliadoParameter = num_afiliado != null ?
                new ObjectParameter("num_afiliado", num_afiliado) :
                new ObjectParameter("num_afiliado", typeof(string));
    
            var serie_consecutivoParameter = serie_consecutivo != null ?
                new ObjectParameter("serie_consecutivo", serie_consecutivo) :
                new ObjectParameter("serie_consecutivo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SGA_ACTUALIZAR_ESTATUS_PRODUCTO_AFILIADO", num_afiliadoParameter, serie_consecutivoParameter);
        }
    
        [DbFunction("BMS_DATA_DENTEntities", "F_BUSQUEDA_TICKET")]
        public virtual IQueryable<F_BUSQUEDA_TICKET_Result> F_BUSQUEDA_TICKET(string bUSQUEDA, string pARAMETRO, string eSTATUS)
        {
            var bUSQUEDAParameter = bUSQUEDA != null ?
                new ObjectParameter("BUSQUEDA", bUSQUEDA) :
                new ObjectParameter("BUSQUEDA", typeof(string));
    
            var pARAMETROParameter = pARAMETRO != null ?
                new ObjectParameter("PARAMETRO", pARAMETRO) :
                new ObjectParameter("PARAMETRO", typeof(string));
    
            var eSTATUSParameter = eSTATUS != null ?
                new ObjectParameter("ESTATUS", eSTATUS) :
                new ObjectParameter("ESTATUS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_BUSQUEDA_TICKET_Result>("[BMS_DATA_DENTEntities].[F_BUSQUEDA_TICKET](@BUSQUEDA, @PARAMETRO, @ESTATUS)", bUSQUEDAParameter, pARAMETROParameter, eSTATUSParameter);
        }
    
        public virtual int SGA_CAMBIAR_AFILIADO(string oLD_AFILIADO, string n_AFILIADO, string cONTACTO, string cOMERCIO, string tELEFONO, string pROVINCIA, string cANTON, string dISTRITO, string dIRECCION, string rEFERENCIA)
        {
            var oLD_AFILIADOParameter = oLD_AFILIADO != null ?
                new ObjectParameter("OLD_AFILIADO", oLD_AFILIADO) :
                new ObjectParameter("OLD_AFILIADO", typeof(string));
    
            var n_AFILIADOParameter = n_AFILIADO != null ?
                new ObjectParameter("N_AFILIADO", n_AFILIADO) :
                new ObjectParameter("N_AFILIADO", typeof(string));
    
            var cONTACTOParameter = cONTACTO != null ?
                new ObjectParameter("CONTACTO", cONTACTO) :
                new ObjectParameter("CONTACTO", typeof(string));
    
            var cOMERCIOParameter = cOMERCIO != null ?
                new ObjectParameter("COMERCIO", cOMERCIO) :
                new ObjectParameter("COMERCIO", typeof(string));
    
            var tELEFONOParameter = tELEFONO != null ?
                new ObjectParameter("TELEFONO", tELEFONO) :
                new ObjectParameter("TELEFONO", typeof(string));
    
            var pROVINCIAParameter = pROVINCIA != null ?
                new ObjectParameter("PROVINCIA", pROVINCIA) :
                new ObjectParameter("PROVINCIA", typeof(string));
    
            var cANTONParameter = cANTON != null ?
                new ObjectParameter("CANTON", cANTON) :
                new ObjectParameter("CANTON", typeof(string));
    
            var dISTRITOParameter = dISTRITO != null ?
                new ObjectParameter("DISTRITO", dISTRITO) :
                new ObjectParameter("DISTRITO", typeof(string));
    
            var dIRECCIONParameter = dIRECCION != null ?
                new ObjectParameter("DIRECCION", dIRECCION) :
                new ObjectParameter("DIRECCION", typeof(string));
    
            var rEFERENCIAParameter = rEFERENCIA != null ?
                new ObjectParameter("REFERENCIA", rEFERENCIA) :
                new ObjectParameter("REFERENCIA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SGA_CAMBIAR_AFILIADO", oLD_AFILIADOParameter, n_AFILIADOParameter, cONTACTOParameter, cOMERCIOParameter, tELEFONOParameter, pROVINCIAParameter, cANTONParameter, dISTRITOParameter, dIRECCIONParameter, rEFERENCIAParameter);
        }
    
        [DbFunction("BMS_DATA_DENTEntities", "F_TICKETS_AFILIADO")]
        public virtual IQueryable<F_TICKETS_AFILIADO_Result> F_TICKETS_AFILIADO(string n_AFILIADO2)
        {
            var n_AFILIADO2Parameter = n_AFILIADO2 != null ?
                new ObjectParameter("N_AFILIADO2", n_AFILIADO2) :
                new ObjectParameter("N_AFILIADO2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_TICKETS_AFILIADO_Result>("[BMS_DATA_DENTEntities].[F_TICKETS_AFILIADO](@N_AFILIADO2)", n_AFILIADO2Parameter);
        }
    
        [DbFunction("BMS_DATA_DENTEntities", "F_BUSQUEDA_SERIE")]
        public virtual IQueryable<F_BUSQUEDA_SERIE_Result> F_BUSQUEDA_SERIE(string bUSQUEDA)
        {
            var bUSQUEDAParameter = bUSQUEDA != null ?
                new ObjectParameter("BUSQUEDA", bUSQUEDA) :
                new ObjectParameter("BUSQUEDA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_BUSQUEDA_SERIE_Result>("[BMS_DATA_DENTEntities].[F_BUSQUEDA_SERIE](@BUSQUEDA)", bUSQUEDAParameter);
        }
    
        [DbFunction("BMS_DATA_DENTEntities", "F_HISTORIAL_SERIE")]
        public virtual IQueryable<F_HISTORIAL_SERIE_Result1> F_HISTORIAL_SERIE(string sERIAL)
        {
            var sERIALParameter = sERIAL != null ?
                new ObjectParameter("SERIAL", sERIAL) :
                new ObjectParameter("SERIAL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_HISTORIAL_SERIE_Result1>("[BMS_DATA_DENTEntities].[F_HISTORIAL_SERIE](@SERIAL)", sERIALParameter);
        }
    
        [DbFunction("BMS_DATA_DENTEntities", "F_OBTENER_RESUMEN_TICKETS")]
        public virtual IQueryable<F_OBTENER_RESUMEN_TICKETS_Result> F_OBTENER_RESUMEN_TICKETS(string cod_tec, Nullable<int> dias_h, string parametro)
        {
            var cod_tecParameter = cod_tec != null ?
                new ObjectParameter("cod_tec", cod_tec) :
                new ObjectParameter("cod_tec", typeof(string));
    
            var dias_hParameter = dias_h.HasValue ?
                new ObjectParameter("dias_h", dias_h) :
                new ObjectParameter("dias_h", typeof(int));
    
            var parametroParameter = parametro != null ?
                new ObjectParameter("parametro", parametro) :
                new ObjectParameter("parametro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_OBTENER_RESUMEN_TICKETS_Result>("[BMS_DATA_DENTEntities].[F_OBTENER_RESUMEN_TICKETS](@cod_tec, @dias_h, @parametro)", cod_tecParameter, dias_hParameter, parametroParameter);
        }
    
        [DbFunction("BMS_DATA_DENTEntities", "F_INVENTARIO_CREDOMATIC")]
        public virtual IQueryable<F_INVENTARIO_CREDOMATIC_Result> F_INVENTARIO_CREDOMATIC(string mES, string aNO, string pARAMETRO, string p_CONSULTA)
        {
            var mESParameter = mES != null ?
                new ObjectParameter("MES", mES) :
                new ObjectParameter("MES", typeof(string));
    
            var aNOParameter = aNO != null ?
                new ObjectParameter("ANO", aNO) :
                new ObjectParameter("ANO", typeof(string));
    
            var pARAMETROParameter = pARAMETRO != null ?
                new ObjectParameter("PARAMETRO", pARAMETRO) :
                new ObjectParameter("PARAMETRO", typeof(string));
    
            var p_CONSULTAParameter = p_CONSULTA != null ?
                new ObjectParameter("P_CONSULTA", p_CONSULTA) :
                new ObjectParameter("P_CONSULTA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_INVENTARIO_CREDOMATIC_Result>("[BMS_DATA_DENTEntities].[F_INVENTARIO_CREDOMATIC](@MES, @ANO, @PARAMETRO, @P_CONSULTA)", mESParameter, aNOParameter, pARAMETROParameter, p_CONSULTAParameter);
        }
    
        [DbFunction("BMS_DATA_DENTEntities", "F_PRODUCTOS_INSTALADOS")]
        public virtual IQueryable<F_PRODUCTOS_INSTALADOS_Result> F_PRODUCTOS_INSTALADOS(Nullable<System.DateTime> f_INICIO, Nullable<System.DateTime> f_FIN)
        {
            var f_INICIOParameter = f_INICIO.HasValue ?
                new ObjectParameter("F_INICIO", f_INICIO) :
                new ObjectParameter("F_INICIO", typeof(System.DateTime));
    
            var f_FINParameter = f_FIN.HasValue ?
                new ObjectParameter("F_FIN", f_FIN) :
                new ObjectParameter("F_FIN", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_PRODUCTOS_INSTALADOS_Result>("[BMS_DATA_DENTEntities].[F_PRODUCTOS_INSTALADOS](@F_INICIO, @F_FIN)", f_INICIOParameter, f_FINParameter);
        }
    
        [DbFunction("BMS_DATA_DENTEntities", "F_REPORTE_MANTENIMIENTO_AFILIADOS")]
        public virtual IQueryable<F_REPORTE_MANTENIMIENTO_AFILIADOS_Result> F_REPORTE_MANTENIMIENTO_AFILIADOS(Nullable<System.DateTime> f_INICIO, Nullable<System.DateTime> f_FIN)
        {
            var f_INICIOParameter = f_INICIO.HasValue ?
                new ObjectParameter("F_INICIO", f_INICIO) :
                new ObjectParameter("F_INICIO", typeof(System.DateTime));
    
            var f_FINParameter = f_FIN.HasValue ?
                new ObjectParameter("F_FIN", f_FIN) :
                new ObjectParameter("F_FIN", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_REPORTE_MANTENIMIENTO_AFILIADOS_Result>("[BMS_DATA_DENTEntities].[F_REPORTE_MANTENIMIENTO_AFILIADOS](@F_INICIO, @F_FIN)", f_INICIOParameter, f_FINParameter);
        }
    
        [DbFunction("BMS_DATA_DENTEntities", "F_INVENTARIO_AFILIADO")]
        public virtual IQueryable<F_INVENTARIO_AFILIADO_Result> F_INVENTARIO_AFILIADO(string n_afiliado)
        {
            var n_afiliadoParameter = n_afiliado != null ?
                new ObjectParameter("n_afiliado", n_afiliado) :
                new ObjectParameter("n_afiliado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_INVENTARIO_AFILIADO_Result>("[BMS_DATA_DENTEntities].[F_INVENTARIO_AFILIADO](@n_afiliado)", n_afiliadoParameter);
        }
    
        [DbFunction("BMS_DATA_DENTEntities", "F_MOVIMIENTOS_POR_PRODUCTOS")]
        public virtual IQueryable<F_MOVIMIENTOS_POR_PRODUCTOS_Result> F_MOVIMIENTOS_POR_PRODUCTOS(string cIA, Nullable<System.DateTime> f_INICIO, Nullable<System.DateTime> f_FIN, string cATEGORIA, string mOVIMIENTO)
        {
            var cIAParameter = cIA != null ?
                new ObjectParameter("CIA", cIA) :
                new ObjectParameter("CIA", typeof(string));
    
            var f_INICIOParameter = f_INICIO.HasValue ?
                new ObjectParameter("F_INICIO", f_INICIO) :
                new ObjectParameter("F_INICIO", typeof(System.DateTime));
    
            var f_FINParameter = f_FIN.HasValue ?
                new ObjectParameter("F_FIN", f_FIN) :
                new ObjectParameter("F_FIN", typeof(System.DateTime));
    
            var cATEGORIAParameter = cATEGORIA != null ?
                new ObjectParameter("CATEGORIA", cATEGORIA) :
                new ObjectParameter("CATEGORIA", typeof(string));
    
            var mOVIMIENTOParameter = mOVIMIENTO != null ?
                new ObjectParameter("MOVIMIENTO", mOVIMIENTO) :
                new ObjectParameter("MOVIMIENTO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_MOVIMIENTOS_POR_PRODUCTOS_Result>("[BMS_DATA_DENTEntities].[F_MOVIMIENTOS_POR_PRODUCTOS](@CIA, @F_INICIO, @F_FIN, @CATEGORIA, @MOVIMIENTO)", cIAParameter, f_INICIOParameter, f_FINParameter, cATEGORIAParameter, mOVIMIENTOParameter);
        }
    
        [DbFunction("BMS_DATA_DENTEntities", "F_AFILIADOS_INSTALACIONES")]
        public virtual IQueryable<F_AFILIADOS_INSTALACIONES_Result> F_AFILIADOS_INSTALACIONES(Nullable<System.DateTime> f_INICIO, Nullable<System.DateTime> f_FIN, string sTATUS)
        {
            var f_INICIOParameter = f_INICIO.HasValue ?
                new ObjectParameter("F_INICIO", f_INICIO) :
                new ObjectParameter("F_INICIO", typeof(System.DateTime));
    
            var f_FINParameter = f_FIN.HasValue ?
                new ObjectParameter("F_FIN", f_FIN) :
                new ObjectParameter("F_FIN", typeof(System.DateTime));
    
            var sTATUSParameter = sTATUS != null ?
                new ObjectParameter("STATUS", sTATUS) :
                new ObjectParameter("STATUS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_AFILIADOS_INSTALACIONES_Result>("[BMS_DATA_DENTEntities].[F_AFILIADOS_INSTALACIONES](@F_INICIO, @F_FIN, @STATUS)", f_INICIOParameter, f_FINParameter, sTATUSParameter);
        }
    
        [DbFunction("BMS_DATA_DENTEntities", "F_SGA_PRODUCTOS_POR_CLIENTE")]
        public virtual IQueryable<F_SGA_PRODUCTOS_POR_CLIENTE_Result> F_SGA_PRODUCTOS_POR_CLIENTE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_SGA_PRODUCTOS_POR_CLIENTE_Result>("[BMS_DATA_DENTEntities].[F_SGA_PRODUCTOS_POR_CLIENTE]()");
        }
    
        [DbFunction("BMS_DATA_DENTEntities", "F_SGA_AFILIADOS_SIN_MANTENIMIENTO")]
        public virtual IQueryable<F_SGA_AFILIADOS_SIN_MANTENIMIENTO_Result> F_SGA_AFILIADOS_SIN_MANTENIMIENTO(string mESES)
        {
            var mESESParameter = mESES != null ?
                new ObjectParameter("MESES", mESES) :
                new ObjectParameter("MESES", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_SGA_AFILIADOS_SIN_MANTENIMIENTO_Result>("[BMS_DATA_DENTEntities].[F_SGA_AFILIADOS_SIN_MANTENIMIENTO](@MESES)", mESESParameter);
        }
    
        [DbFunction("BMS_DATA_DENTEntities", "F_BUSQUEDA_AFILIADO")]
        public virtual IQueryable<F_BUSQUEDA_AFILIADO_Result> F_BUSQUEDA_AFILIADO(string bUSQUEDA, string pARAMETRO, string eSTATUS)
        {
            var bUSQUEDAParameter = bUSQUEDA != null ?
                new ObjectParameter("BUSQUEDA", bUSQUEDA) :
                new ObjectParameter("BUSQUEDA", typeof(string));
    
            var pARAMETROParameter = pARAMETRO != null ?
                new ObjectParameter("PARAMETRO", pARAMETRO) :
                new ObjectParameter("PARAMETRO", typeof(string));
    
            var eSTATUSParameter = eSTATUS != null ?
                new ObjectParameter("ESTATUS", eSTATUS) :
                new ObjectParameter("ESTATUS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<F_BUSQUEDA_AFILIADO_Result>("[BMS_DATA_DENTEntities].[F_BUSQUEDA_AFILIADO](@BUSQUEDA, @PARAMETRO, @ESTATUS)", bUSQUEDAParameter, pARAMETROParameter, eSTATUSParameter);
        }
    }
}
