//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Activos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_PROD
    {
        public string CIA { get; set; }
        public string COD_PROD { get; set; }
        public string COD_FAMI { get; set; }
        public string COD_SUBF { get; set; }
        public string COD_DEPA { get; set; }
        public string COD_ADIC { get; set; }
        public string NOMBRE_1 { get; set; }
        public string NOMBRE_2 { get; set; }
        public string LOCALIZACION { get; set; }
        public string UNI_MED { get; set; }
        public decimal VOLUMEN { get; set; }
        public decimal PESO { get; set; }
        public Nullable<System.DateTime> ULTIMO_D { get; set; }
        public Nullable<System.DateTime> ULTIMO_H { get; set; }
        public string IMP_1 { get; set; }
        public string IMP_2 { get; set; }
        public string IMP_3 { get; set; }
        public string IMP_4 { get; set; }
        public string CUENTA_D { get; set; }
        public string CUENTA_H { get; set; }
        public string ACTIVO { get; set; }
        public decimal DESC_MAX { get; set; }
        public decimal UTIL_MIN { get; set; }
        public decimal UTIL_P1 { get; set; }
        public decimal UTIL_P2 { get; set; }
        public decimal UTIL_P3 { get; set; }
        public decimal UTIL_P4 { get; set; }
        public decimal UTIL_P5 { get; set; }
        public decimal UTIL_P6 { get; set; }
        public decimal UTIL_P7 { get; set; }
        public decimal UTIL_P8 { get; set; }
        public decimal UTIL_P9 { get; set; }
        public decimal PRECIO_1 { get; set; }
        public decimal PRECIO_2 { get; set; }
        public decimal PRECIO_3 { get; set; }
        public decimal PRECIO_4 { get; set; }
        public decimal PRECIO_5 { get; set; }
        public decimal PRECIO_6 { get; set; }
        public decimal PRECIO_7 { get; set; }
        public decimal PRECIO_8 { get; set; }
        public Nullable<decimal> PRECIO_9 { get; set; }
        public Nullable<decimal> MINIMO { get; set; }
        public Nullable<decimal> MAXIMO { get; set; }
        public Nullable<decimal> PEDIDOS { get; set; }
        public Nullable<decimal> COMPRAS { get; set; }
        public Nullable<decimal> ULTIMO_L { get; set; }
        public Nullable<decimal> ULTIMO_E { get; set; }
        public string SERIE { get; set; }
        public string GARANTIA { get; set; }
        public Nullable<int> MESES_GARANTIA { get; set; }
        public string ULT_COD_PROV { get; set; }
        public Nullable<int> CANTIDAD_DIAS { get; set; }
        public string LOCALIZACION_2 { get; set; }
        public string PROMOCION { get; set; }
        public Nullable<decimal> DESC_PROM { get; set; }
        public Nullable<System.DateTime> PROM_DEL { get; set; }
        public Nullable<System.DateTime> PROM_AL { get; set; }
        public string IMP_PART { get; set; }
        public Nullable<decimal> PRODUCIR_1 { get; set; }
        public Nullable<decimal> PRODUCIR_2 { get; set; }
        public Nullable<decimal> PRODUCIR_3 { get; set; }
        public string COD_UBIC { get; set; }
        public string PEDIR { get; set; }
        public Nullable<decimal> ULTIMO_FOB { get; set; }
        public string COD_BARRAS { get; set; }
        public string NOTAS { get; set; }
        public string ID_ABC { get; set; }
        public string ID_INDICADOR { get; set; }
        public string FOTO { get; set; }
        public Nullable<decimal> COMPRAS_MOVIL { get; set; }
        public string COMISION { get; set; }
    }
}
