//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Activos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_MOVS
    {
        public string CIA { get; set; }
        public string COD_TIPO { get; set; }
        public string NUM_DOC { get; set; }
        public string COD_PROD { get; set; }
        public int CONSECUTIVO { get; set; }
        public string SERIE { get; set; }
        public string NOTAS { get; set; }
        public string PEDIDO { get; set; }
    }
}
