//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Activos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_TECN
    {
        public string CIA { get; set; }
        public string COD_TECN { get; set; }
        public string DES_TECN { get; set; }
        public Nullable<decimal> POR_COMI { get; set; }
    }
}
