//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Activos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_MOV1
    {
        public string CIA { get; set; }
        public string MES_PROC { get; set; }
        public string ANO_PROC { get; set; }
        public string COD_TIPO { get; set; }
        public string NUM_DOC { get; set; }
        public decimal CONSECUTIVO { get; set; }
        public System.DateTime FECHA { get; set; }
        public System.DateTime FECHA_DIG { get; set; }
        public string USUARIO { get; set; }
        public string COD_AUX1 { get; set; }
        public string COD_AUX2 { get; set; }
        public string SISTEMA { get; set; }
        public Nullable<decimal> CAMBIO { get; set; }
        public Nullable<decimal> COSTO_L { get; set; }
        public Nullable<decimal> COSTO_E { get; set; }
        public Nullable<decimal> BRUTO { get; set; }
        public Nullable<decimal> BRUTO_EX { get; set; }
        public Nullable<decimal> BRUTO_GR { get; set; }
        public Nullable<decimal> IMP_1 { get; set; }
        public Nullable<decimal> IMP_2 { get; set; }
        public Nullable<decimal> IMP_3 { get; set; }
        public Nullable<decimal> IMP_4 { get; set; }
        public Nullable<decimal> DESCUENTO { get; set; }
        public Nullable<decimal> DESCUENTO_EX { get; set; }
        public Nullable<decimal> DESCUENTO_GR { get; set; }
        public Nullable<decimal> NETO { get; set; }
        public Nullable<decimal> NETO_EX { get; set; }
        public Nullable<decimal> NETO_GR { get; set; }
        public string NULO { get; set; }
        public string NOTAS { get; set; }
        public string CIA_CXP { get; set; }
        public string COD_PROV { get; set; }
        public string TIPO_CREDITO { get; set; }
        public Nullable<System.DateTime> F_VENCE { get; set; }
        public string REFERENCIA { get; set; }
        public Nullable<decimal> ADI1 { get; set; }
        public Nullable<decimal> ADI2 { get; set; }
        public Nullable<decimal> ADI3 { get; set; }
        public string ADI4 { get; set; }
        public string ADI5 { get; set; }
        public string ADI6 { get; set; }
        public string ADI7 { get; set; }
        public string ADI8 { get; set; }
        public Nullable<System.DateTime> ADI9 { get; set; }
        public Nullable<System.DateTime> ADI10 { get; set; }
        public Nullable<System.DateTime> ADI11 { get; set; }
        public string COD_VEND { get; set; }
        public string COD_RUTA { get; set; }
        public string NIVEL_PRECIO { get; set; }
        public string COD_FPAG { get; set; }
        public string CIA_FAC { get; set; }
        public string DETALLE { get; set; }
        public string MONEDA { get; set; }
        public string IMPRIMIR_SERV { get; set; }
        public string CONFIRMADO { get; set; }
        public string USER_CONFIRMA { get; set; }
        public Nullable<System.DateTime> DIA_CONFIRMA { get; set; }
        public string STATUS_ENT { get; set; }
        public string MOTIVO { get; set; }
        public string X { get; set; }
        public string Y { get; set; }
    }
}
