//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Activos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_GARA
    {
        public string CIA { get; set; }
        public string NUM_DOC_GARANTIA { get; set; }
        public System.DateTime FECHA_INGRESO { get; set; }
        public string TIPO_GARANTIA { get; set; }
        public string COD_CLIE { get; set; }
        public string NOTA_1 { get; set; }
        public string CODIGO_BOLETA { get; set; }
        public string TECNICO { get; set; }
        public Nullable<System.DateTime> FECHA_ENTREGA { get; set; }
        public string PROBLEMA_1 { get; set; }
        public string PROBLEMA_2 { get; set; }
        public string PROBLEMA_3 { get; set; }
        public string PROBLEMA_4 { get; set; }
        public string SOLUCION_1 { get; set; }
        public string SOLUCION_2 { get; set; }
        public string SOLUCION_3 { get; set; }
        public string SOLUCION_4 { get; set; }
        public string STATUS { get; set; }
        public string RMA { get; set; }
        public string CONTACTO { get; set; }
        public string TELEFONO { get; set; }
        public string HORA { get; set; }
        public Nullable<System.DateTime> FECHA_REPARADO { get; set; }
        public string RECIBE { get; set; }
        public string ORDEN_COMPRA { get; set; }
        public string USUARIO { get; set; }
        public string FACTURADO { get; set; }
        public string FACTURA { get; set; }
        public Nullable<decimal> MANO_OBRA { get; set; }
        public Nullable<decimal> MATERIALES { get; set; }
        public string N_COORDINA { get; set; }
        public string N_EJECUTIVO { get; set; }
        public string N_AFILIADO { get; set; }
        public string N_CLIENTE { get; set; }
        public string N_DIRECCION { get; set; }
        public string N_HORA_P { get; set; }
        public Nullable<System.DateTime> N_FECHA_P { get; set; }
        public Nullable<decimal> N_CANTIDAD { get; set; }
        public string N_TECNICO { get; set; }
        public string N_TIPO { get; set; }
        public string N_INTERNET { get; set; }
        public string N_MUEBLE { get; set; }
        public string N_ELECTRICIDAD { get; set; }
        public string N_COD_PROV { get; set; }
        public string N_COD_CANT { get; set; }
        public string N_COD_DIST { get; set; }
        public string TIPO_EVENTO { get; set; }
        public Nullable<System.DateTime> FECHA_DIAGNOSTICADO { get; set; }
    }
}
