//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Activos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_GARV
    {
        public string CIA { get; set; }
        public string NUM_DOC_GARANTIA { get; set; }
        public int SECUENCIA { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string HORA { get; set; }
        public string DETALLE1 { get; set; }
        public string DETALLE2 { get; set; }
        public string DETALLE3 { get; set; }
        public string CONFIDENCIAL { get; set; }
    }
}
