//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Activos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGA_ROLES_PERMISOS
    {
        public int ID { get; set; }
        public int ID_PERMISO { get; set; }
        public int ID_ROL { get; set; }
    
        public virtual SGA_PERMISOS SGA_PERMISOS { get; set; }
        public virtual SGA_ROLES SGA_ROLES { get; set; }
    }
}
