//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Activos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGA_BITACORA_TICKET
    {
        public int ID { get; set; }
        public string ID_TICKET { get; set; }
        public string TIPO_MOVIMIENTO { get; set; }
        public string AVERIA_REPORTADA { get; set; }
        public string DIAGNOSTICO { get; set; }
        public string SOLUCION { get; set; }
        public string EXPOSICION_EQUIPO { get; set; }
        public string EXPOSICION_EQUIPO_2 { get; set; }
        public string MANTENIMIENTO { get; set; }
        public string PRUEBAS { get; set; }
        public string TIPO_CONEXION { get; set; }
        public string DETALLE_INSTALACION { get; set; }
        public string EXPOSICION_EQUIPO_VISITA { get; set; }
        public string OTROS { get; set; }
        public Nullable<System.DateTime> FECHA_DIG { get; set; }
        public string EXTRA_1 { get; set; }
        public string EXTRA_2 { get; set; }
        public string EXTRA_3 { get; set; }
    }
}
