//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Activos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGA_ESTADO_PRODUCTOS
    {
        public int ID { get; set; }
        public int SERIE_CONSECUTIVO { get; set; }
        public string COD_PROD { get; set; }
        public string ID_BOLETA { get; set; }
        public string ESTADO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string ACCION { get; set; }
    }
}
