//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Activos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGA_EVIDENCIA_TICKET
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string PATH { get; set; }
        public string EXTENSION { get; set; }
        public string MEMBERSHIP_ID { get; set; }
        public string ID_TICKET { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public Nullable<System.DateTime> UPDATED { get; set; }
        public string DESCRIPTION { get; set; }
    }
}
