//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Activos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGA_USUARIOS
    {
        public int ID { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public string CONTRASENA { get; set; }
        public System.DateTime FECHA_REGISTRO { get; set; }
        public int ROL { get; set; }
        public bool ACTIVO { get; set; }
        public string USER_LOGIN { get; set; }
        public string COD_TECNICO { get; set; }
    
        public virtual SGA_ROLES SGA_ROLES { get; set; }
    }
}
