//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Activos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGA_AFILIADOS
    {
        public int ID { get; set; }
        public string N_AFILIADO { get; set; }
        public string NOMBRE { get; set; }
        public string DIRECCION_1 { get; set; }
        public string DIRECCION_2 { get; set; }
        public string NOMBRE_NEGOCIO { get; set; }
        public string TELEFONO { get; set; }
        public string N_COD_PROV { get; set; }
        public string N_COD_CANT { get; set; }
        public string N_COD_DIST { get; set; }
        public Nullable<bool> ACTUALIZADO { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
        public string ANTIGUO_N_AFILIADO { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public string EXTRA_1 { get; set; }
        public string EXTRA_2 { get; set; }
        public Nullable<System.DateTime> FECHA_INACTIVACION { get; set; }
        public Nullable<bool> INVENTARIO_ACTUALIZADO { get; set; }
        public string ESTATUS { get; set; }
    }
}
