//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Activos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEB_Distrito
    {
        public string idProvincia { get; set; }
        public string idCanton { get; set; }
        public string idDistrito { get; set; }
        public string nombreDistrito { get; set; }
    }
}
